BOOTLOADER = atmel-dfu

LTO_ENABLE      = yes
TAP_DANCE_ENABLE = yes
KEY_OVERRIDE_ENABLE = no 
CAPS_WORD_ENABLE = no
MOUSEKEY_ENABLE = no

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
COMBO_ENABLE = no

OLED_ENABLE     = yes
OLED_DRIVER     = SSD1306

RGBLIGHT_ENABLE = yes
RGB_MATRIX_ENABLE = no
